# Generated by Django 5.1.1 on 2024-10-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEN', models.CharField(max_length=100, verbose_name='ชื่ออังกฤษ')),
                ('nameTH', models.CharField(max_length=100, verbose_name='ชื่อไทย')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โต๊ะ')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('IT', 'IT'), ('user', 'User')], max_length=10, verbose_name='ระดับผู้ใช้งาน')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ชื่อผู้ใช้งาน')),
                ('password', models.CharField(max_length=128, verbose_name='รหัสผ่าน')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='user_management.department', verbose_name='ฝ่าย')),
            ],
        ),
    ]
