# Generated by Django 5.1.1 on 2024-11-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], max_length=10, verbose_name='ระดับผู้ใช้งาน'),
        ),
    ]
