# Generated by Django 5.1.1 on 2024-11-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='ชื่อกลาง'),
        ),
    ]
