# Generated by Django 5.1.4 on 2024-12-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nameEN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่ออังกฤษ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nameTH',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อไทย'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='รหัสผ่าน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='ชื่อผู้ใช้งาน'),
        ),
    ]
