# Generated by Django 5.1.1 on 2024-10-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_type', models.CharField(choices=[('do_it_yourself', 'Do It Yourself'), ('claim', 'Send for Claim')], max_length=50)),
                ('repair_details', models.TextField()),
                ('repair_status', models.BooleanField(default=False)),
                ('date_repaired', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_description', models.TextField()),
                ('claim_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_requests.repair')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=100)),
                ('request_description', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('repair_type', models.CharField(blank=True, choices=[('do_it_yourself', 'Do It Yourself'), ('claim', 'Send for Claim')], max_length=50, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_requests.servicerequest'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_requests.servicerequest')),
            ],
        ),
    ]
