# Generated by Django 5.1.1 on 2024-10-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_remove_repair_date_repaired_remove_repair_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/files/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='repair_by',
            field=models.CharField(choices=[('do_it_yourself', 'ซ่อมโดยฝ่ายเทคโนโลยีสารสนเทศ'), ('claim', 'ส่งเคลม')], default='do_it_yourself', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='repair_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='repair_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
