# Generated by Django 5.1.1 on 2024-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_servicerequest_attached_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_request_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='repair_by',
            field=models.CharField(choices=[('ซ่อมโดยฝ่ายเทคโนโลยีสารสนเทศ', 'ซ่อมโดยฝ่ายเทคโนโลยีสารสนเทศ'), ('ส่งเคลม', 'ส่งเคลม')], max_length=50),
        ),
    ]
