# Generated by Django 5.1.1 on 2024-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_servicerequest_service_request_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_request_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
