# Generated by Django 5.1.1 on 2024-10-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_requeststatus_servicerequestconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='repair_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
