# Generated by Django 5.1.1 on 2024-10-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0011_alter_servicerequest_total_repair_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='date_completed',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='date_received',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
