# Generated by Django 5.1.1 on 2024-10-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0012_alter_servicerequest_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
