# Generated by Django 5.1.1 on 2024-10-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0014_alter_servicerequest_repair_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='equipment',
        ),
    ]
