# Generated by Django 5.1.1 on 2024-11-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0015_remove_servicerequest_equipment'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='repair_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_requests.requeststatus'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user_department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.user'),
        ),
    ]
