# Generated by Django 5.1.1 on 2024-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0021_repairupdatelog_change_device_repairupdatelog_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='change_device',
            field=models.BooleanField(default=False, verbose_name='เปลี่ยนอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ค่าใช้จ่าย'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='equipment_new',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสอุปกรณ์ใหม่'),
        ),
    ]
