# Generated by Django 5.1.4 on 2024-12-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0029_alter_servicerequest_total_repair_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='วันที่อัปเดต')),
                ('details', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='service_requests.repairclaim', verbose_name='การเคลม')),
            ],
        ),
    ]
