# Generated by Django 5.1.1 on 2024-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('notebooke', 'Notebook'), ('computer', 'Computer'), ('printer', 'Printer'), ('network_device', 'Network Device')], max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiration', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
