# Generated by Django 5.1.1 on 2024-11-06 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0004_scanner_ups'),
        ('repair_management', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='สภาพอุปกรณ์')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='สถานะอุปกรณ์')),
            ],
        ),
        migrations.RemoveField(
            model_name='computer',
            name='model',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ram_size',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='storage_size',
        ),
        migrations.AddField(
            model_name='computer',
            name='equipment_condition',
            field=models.CharField(default='New', max_length=255, verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='computer',
            name='equipment_status',
            field=models.CharField(default='in_use', max_length=255, verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='computer',
            name='internet_connection',
            field=models.BooleanField(default=False, verbose_name='เชื่อมต่อ Internet'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='keyboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.keyboard', verbose_name='keyboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='keyboard_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='license_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.monitor', verbose_name='monitor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.mouse', verbose_name='mouse'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='อื่นๆ'),
        ),
        migrations.AddField(
            model_name='computer',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.printer', verbose_name='printer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='printer_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.scanner', verbose_name='Scanner'),
        ),
        migrations.AddField(
            model_name='computer',
            name='scanner_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.software', verbose_name='software license'),
        ),
        migrations.AddField(
            model_name='computer',
            name='software_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='spec',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.ups', verbose_name='UPS'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ups_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repair_management.vendor', verbose_name='vendor'),
        ),
    ]
