# Generated by Django 5.1.1 on 2024-11-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0005_equipmentcondition_equipmentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='equipment_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='equipment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
    ]
