# Generated by Django 5.1.1 on 2024-11-07 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0007_alter_computer_equipment_condition_and_more'),
        ('repair_management', '0002_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='purchase_date',
            new_name='warranty',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='screen_size',
        ),
        migrations.AddField(
            model_name='monitor',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='equipment_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='equipment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='repair_management.vendor'),
        ),
    ]
