# Generated by Django 5.1.1 on 2024-11-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0008_rename_purchase_date_monitor_warranty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='equipment_condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='equipment_status',
            new_name='status',
        ),
    ]
