# Generated by Django 5.1.1 on 2024-11-12 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0009_rename_equipment_condition_monitor_condition_and_more'),
        ('repair_management', '0002_vendor'),
        ('user_management', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='mouse',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouses', to='repair_management.vendor'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouses', to='equipment_management.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouses', to='user_management.user'),
        ),
    ]
