# Generated by Django 5.1.1 on 2024-11-12 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0011_remove_mouse_status_remove_mouse_vendor'),
        ('repair_management', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouses', to='repair_management.vendor'),
        ),
    ]
