# Generated by Django 5.1.1 on 2024-11-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0012_mouse_status_mouse_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
    ]
