# Generated by Django 5.1.1 on 2024-11-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0013_mouse_condition'),
        ('repair_management', '0002_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboards', to='repair_management.vendor'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('wired', 'Wired'), ('wireless', 'Wireless')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('wired', 'Wired'), ('wireless', 'Wireless')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
