# Generated by Django 5.1.1 on 2024-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0015_remove_printer_name_remove_printer_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
