# Generated by Django 5.1.1 on 2024-11-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0016_printer_ip_address'),
        ('repair_management', '0002_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='scan_type',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='scanner',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scanner',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanners', to='repair_management.vendor'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
