# Generated by Django 5.1.1 on 2024-11-14 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0017_remove_scanner_name_remove_scanner_purchase_date_and_more'),
        ('repair_management', '0002_vendor'),
        ('user_management', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ups',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ups',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='ups',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='ups',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ups',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='ups',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upses', to='repair_management.vendor'),
        ),
        migrations.AddField(
            model_name='ups',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ups',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upses', to='equipment_management.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upses', to='user_management.user'),
        ),
    ]
