# Generated by Django 5.1.1 on 2024-11-14 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0018_remove_ups_name_remove_ups_purchase_date_and_more'),
        ('repair_management', '0002_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='brand',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='server',
            name='model',
        ),
        migrations.RemoveField(
            model_name='server',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ram_size',
        ),
        migrations.RemoveField(
            model_name='server',
            name='storage_size',
        ),
        migrations.AddField(
            model_name='server',
            name='ibm_warranty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='spec',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='server',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='repair_management.vendor'),
        ),
        migrations.AddField(
            model_name='server',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
