# Generated by Django 5.1.1 on 2024-11-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0019_rename_brand_server_serial_number_remove_server_cpu_and_more'),
        ('repair_management', '0002_vendor'),
        ('user_management', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('computer', 'Computer'), ('printer', 'Printer'), ('network_device', 'Network Device')], max_length=50),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty', models.DateField(blank=True, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='equipment_management.equipmenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networks', to='user_management.user')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentstatus', verbose_name='สถานะอุปกรณ์')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networks', to='repair_management.vendor')),
            ],
        ),
    ]
