# Generated by Django 5.1.1 on 2024-11-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0024_remove_groupprogram_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprogram',
            name='equipment_type',
        ),
    ]
