# Generated by Django 5.1.1 on 2024-11-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0025_remove_groupprogram_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprogram',
            name='license_key',
        ),
        migrations.AddField(
            model_name='software',
            name='group_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='equipment_management.groupprogram'),
        ),
    ]
