# Generated by Django 5.1.1 on 2024-11-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0026_remove_groupprogram_license_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprogram',
            name='equipment_code',
        ),
    ]
