# Generated by Django 5.1.1 on 2024-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0027_remove_groupprogram_equipment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
