# Generated by Django 5.1.1 on 2024-11-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0028_software_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='equipment_type',
        ),
    ]
