# Generated by Django 5.1.1 on 2024-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0029_remove_software_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โปรแกรมพิเศษ'),
        ),
    ]
