# Generated by Django 5.1.1 on 2024-11-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0030_computer_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_software', to='equipment_management.computer'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='equipment_management.software', verbose_name='software license'),
        ),
    ]
