# Generated by Django 5.1.1 on 2024-11-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0032_remove_computer_software_computer_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='software',
        ),
        migrations.AddField(
            model_name='computer',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='equipment_management.software', verbose_name='software license'),
        ),
    ]
