# Generated by Django 5.1.1 on 2024-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0033_remove_computer_software_computer_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
