# Generated by Django 5.1.1 on 2024-11-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0034_alter_computer_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameracctv',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
