# Generated by Django 5.1.1 on 2024-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0035_alter_cameracctv_ip_address_alter_network_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
