# Generated by Django 5.1.1 on 2024-11-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0036_computer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
