# Generated by Django 5.1.4 on 2024-12-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0037_alter_computer_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_license_key', models.CharField(max_length=250)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.computer')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.software')),
            ],
        ),
    ]
