# Generated by Django 5.1.4 on 2024-12-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0038_computersoftware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerSoftware',
        ),
    ]
