# Generated by Django 5.1.4 on 2024-12-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0039_delete_computersoftware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='equipment_management.software'),
        ),
    ]
