# Generated by Django 5.1.4 on 2024-12-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0041_alter_computer_owner_alter_computer_software_and_more'),
        ('user_management', '0004_alter_user_nameen_alter_user_nameth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='user_management.user'),
        ),
        migrations.RemoveField(
            model_name='computer',
            name='software',
        ),
        migrations.AlterField(
            model_name='software',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='user_management.user'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='software',
            field=models.ManyToManyField(blank=True, related_name='software_computers', to='equipment_management.software'),
        ),
    ]
