# Generated by Django 5.1.4 on 2024-12-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0042_alter_computer_owner_remove_computer_software_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='license_key',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='software_name',
        ),
    ]
