# Generated by Django 5.1.4 on 2024-12-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0044_other_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameracctv',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='other',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.equipmentcondition', verbose_name='สภาพอุปกรณ์'),
        ),
    ]
