# Generated by Django 5.1.4 on 2024-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0045_cameracctv_condition_other_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='status',
            field=models.CharField(blank=True, choices=[('enable', 'ใช้งาน'), ('disable', 'ว่าง')], max_length=20, null=True),
        ),
    ]
