# Generated by Django 5.1.4 on 2024-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0046_software_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
