# Generated by Django 5.1.4 on 2024-12-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0047_software_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='status',
            field=models.CharField(blank=True, choices=[('enable', 'enable'), ('disable', 'disable')], max_length=20, null=True),
        ),
    ]
