# Generated by Django 5.1.4 on 2024-12-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0049_softwaretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='equipment_management.softwaretype'),
        ),
    ]
