from django.urls import path
from .views import (camera_cctv_create, camera_cctv_delete, camera_cctv_list, camera_cctv_update, computer_create, computer_delete, computer_list, computer_update, equipment_list, 
                    equipment_create, equipment_update, equipment_delete, get_keyboard_details, get_mouse_details, get_owner_details, get_printer_details, get_scanner_details, get_software_details, get_ups_details, 
                    keyboard_create, keyboard_delete, keyboard_list, keyboard_update, monitor_create, monitor_list, monitor_delete, monitor_update, mouse_create, mouse_delete, 
                    mouse_list, mouse_update, network_create, network_delete, network_list, network_update, printer_create, printer_delete, printer_list, printer_update, scanner_create, scanner_delete, scanner_list, 
                    scanner_update, server_list, server_create, server_update, server_delete, software_create, software_delete, software_list, software_update, ups_create, ups_delete, ups_list, ups_update, get_monitor_details)

urlpatterns = [
    path('', equipment_list, name='equipment_list'),
    path('create/', equipment_create, name='equipment_create'),
    path('update/<int:pk>/', equipment_update, name='equipment_update'),
    path('delete/<int:pk>/', equipment_delete, name='equipment_delete'),
    path('computers/', computer_list, name='computer_list'),
    path('computer/create/', computer_create, name='computer_create'),
    path('computer/update/<int:pk>/', computer_update, name='computer_update'),
    path('computer/delete/<int:pk>/', computer_delete, name='computer_delete'),
    path('monitors/', monitor_list, name='monitor_list'),
    path('monitors/create/', monitor_create, name='monitor_create'),
    path('monitors/update/<int:pk>/', monitor_update, name='monitor_update'),
    path('monitors/delete/<int:pk>/', monitor_delete, name='monitor_delete'),
    path('mouses/', mouse_list, name='mouse_list'),
    path('mouses/create/', mouse_create, name='mouse_create'),
    path('mouses/update/<int:pk>/', mouse_update, name='mouse_update'),
    path('mouses/delete/<int:pk>/', mouse_delete, name='mouse_delete'),
    path('keyboards/', keyboard_list, name='keyboard_list'),
    path('keyboards/create/', keyboard_create, name='keyboard_create'),
    path('keyboards/update/<int:pk>/', keyboard_update, name='keyboard_update'),
    path('keyboards/delete/<int:pk>/', keyboard_delete, name='keyboard_delete'),
    path('printers/', printer_list, name='printer_list'),
    path('printers/create/', printer_create, name='printer_create'),
    path('printers/update/<int:pk>/', printer_update, name='printer_update'),
    path('printers/delete/<int:pk>/', printer_delete, name='printer_delete'),
    path('scaners/', scanner_list, name='scanner_list'),
    path('scanners/create/', scanner_create, name='scanner_create'),
    path('scanners/update/<int:pk>/', scanner_update, name='scanner_update'),
    path('scanners/delete/<int:pk>/', scanner_delete, name='scanner_delete'),
    path('upses/', ups_list, name='ups_list'),
    path('upses/create/', ups_create, name='ups_create'),
    path('upses/update/<int:pk>/', ups_update, name='ups_update'),
    path('upses/delete/<int:pk>/', ups_delete, name='ups_delete'),
    path('servers/', server_list, name='server_list'),
    path('servers/create/', server_create, name='server_create'),
    path('servers/update/<int:pk>/', server_update, name='server_update'),
    path('servers/delete/<int:pk>/', server_delete, name='server_delete'),
    path('networks/', network_list, name='network_list'),
    path('networks/create/', network_create, name='network_create'),
    path('networks/update/<int:pk>/', network_update, name='network_update'),
    path('networks/delete/<int:pk>/', network_delete, name='network_delete'),
    path('camera_cctvs/', camera_cctv_list, name='camera_cctv_list'),
    path('camera_cctvs/create/', camera_cctv_create, name='camera_cctv_create'),
    path('camera_cctvs/update/<int:pk>/', camera_cctv_update, name='camera_cctv_update'),
    path('camera_cctvs/delete/<int:pk>/', camera_cctv_delete, name='camera_cctv_delete'),
    path('get_monitor_details/<int:monitor_id>/', get_monitor_details, name='get_monitor_details'),
    path('get_mouse_details/<int:mouse_id>/', get_mouse_details, name='get_mouse_details'),
    path('get_keyboard_details/<int:keyboard_id>/', get_keyboard_details, name='get_keyboard_details'),
    path('get_printer_details/<int:printer_id>/', get_printer_details, name='get_printer_details'),
    path('get_scanner_details/<int:scanner_id>/', get_scanner_details, name='get_scanner_details'),
    path('get_ups_details/<int:ups_id>/', get_ups_details, name='get_ups_details'),
    path('get_software_details/<int:software_id>/', get_software_details, name='get_software_details'),
    path('get_owner_details/<int:owner_id>/', get_owner_details, name='get_owner_details'),
    path('softwares/list/', software_list, name='software_list'),
    path('softwares/create/', software_create, name='software_create'),
    path('softwares/update/<int:pk>/', software_update, name='software_update'),
    path('softwares/delete/<int:pk>/', software_delete, name='software_delete'),
]
